[package]
name = "ws-test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21"
futures-util = "0.3"
url = "2"

[[bin]]
name = "ws-echo-server"
path = "src/server.rs"

[[bin]]
name = "ws-test-client"
path = "src/client.rs"
